"use client";

import { useState, useCallback, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { PropertySchema, Property } from "@/schemas/property.schema";
import DashboardShell from "@/components/layout/dashboard-shell";
import { Button } from "@/components/ui/button";
import { usePropertyStore, useStoreHydrated } from "@/store/usestore";

const DIRECTOR_BUTTON_CLASS =
  "h-[48px] w-[200px] rounded-md font-sans font-medium text-white bg-[#003366] hover:bg-[#003366]/90 transition-colors";
const HYDRATION_TIMEOUT_MS = 50;

const ANTIPODEAN_STYLES = [
  { id: "contemporary", label: "Contemporary" },
  { id: "heritage", label: "Heritage" },
  { id: "coastal", label: "Coastal" },
  { id: "urban", label: "Urban" },
] as const;

function downloadPlainText(content: string, filename: string = "listing.txt") {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".txt") ? filename : `${filename}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function DataEntryPage() {
  const hydrated = useStoreHydrated();
  const propertyData = usePropertyStore((s) => s.propertyData);
  const [styleLevel, setStyleLevel] = useState(50);
  const [selectedStyle, setSelectedStyle] = useState<string | null>(null);
  const [generatedText, setGeneratedText] = useState("");
  const [mounted, setMounted] = useState(false);
  const [hydrationTimeout, setHydrationTimeout] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted) return;
    const t = setTimeout(() => setHydrationTimeout(true), HYDRATION_TIMEOUT_MS);
    return () => clearTimeout(t);
  }, [mounted]);

  const { register, formState: { errors } } = useForm<Property>({
    resolver: zodResolver(PropertySchema),
    defaultValues: {
      source: "Manual",
      dataConfidence: 5,
      createdAt: new Date(),
      propertyId: "",
      address: {
        StreetNumber: "",
        StreetName: "",
        City: "",
        StateOrProvince: "",
        PostalCode: "",
        Country: "AU",
      },
      improvements: {},
      land: {},
    },
  });

  const generateFromStore = useCallback(() => {
    const source = propertyData ?? null;
    const parts: string[] = [];
    const addr = source?.address;
    if (addr?.StreetNumber || addr?.StreetName) {
      parts.push([addr?.StreetNumber, addr?.StreetName].filter(Boolean).join(" ").trim());
    }
    if (addr?.City) parts.push(addr.City);
    if (addr?.StateOrProvince) parts.push(addr.StateOrProvince);
    if (addr?.PostalCode) parts.push(addr.PostalCode);
    const imp = source?.improvements;
    if (imp) {
      if (imp.BedroomsTotal != null) parts.push(`${imp.BedroomsTotal} bed(s)`);
      if (imp.BathroomsFull != null) parts.push(`${imp.BathroomsFull} bath(s)`);
      if (imp.LivingArea != null) parts.push(`Living: ${imp.LivingArea} sqft`);
    }
    const styleTag = selectedStyle ? ANTIPODEAN_STYLES.find((s) => s.id === selectedStyle)?.label ?? "" : "";
    const intro = styleTag
      ? `[${styleTag} style, ${styleLevel}%] `
      : `[Style level ${styleLevel}%] `;
    const body = parts.length ? parts.join(" · ") : "No property context — add data on the Property Entry page.";
    setGeneratedText(intro + body + "\n\n— Generated by RealInfo Listing Generator (RESO-compliant).");
  }, [propertyData, selectedStyle, styleLevel]);

  const handleDownloadTxt = useCallback(() => {
    const text = generatedText || "No listing text generated yet. Use the Property Entry page to add data, then generate here.";
    const name = "realinfo-listing.txt";
    downloadPlainText(text, name);
  }, [generatedText]);

  const canRender = mounted && (hydrated || hydrationTimeout);

  if (!canRender) {
    return (
      <DashboardShell>
        <div className="mx-auto max-w-2xl flex items-center justify-center py-12 text-muted-foreground font-sans text-sm">
          Loading…
        </div>
      </DashboardShell>
    );
  }

  return (
    <DashboardShell>
      <div className="mx-auto max-w-2xl">
        <header className="overflow-hidden rounded-lg border border-border bg-primary text-primary-foreground shadow-sm">
          <div className="px-6 py-5">
            <h1 className="text-xl font-bold tracking-tight font-sans sm:text-2xl">
              Listing Generator
            </h1>
            <p className="mt-1 text-sm font-normal text-primary-foreground/80 font-sans">
              RealInfo · RESO-compliant listing copy. Infosource.com.au
            </p>
          </div>
        </header>

        {propertyData && (
          <section className="mt-6 rounded-xl border border-border bg-card shadow-sm overflow-hidden" aria-label="Property summary">
            <div className="border-b border-border bg-muted/30 px-5 py-3">
              <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground font-sans">
                Property summary
              </h2>
            </div>
            <div className="px-5 py-4 space-y-3 text-sm font-sans text-card-foreground">
              <p className="font-medium text-base leading-snug">
                {[propertyData.address?.StreetNumber, propertyData.address?.StreetName].filter(Boolean).join(" ").trim() || "—"}
              </p>
              <p className="text-muted-foreground">
                {[propertyData.address?.City, propertyData.address?.StateOrProvince].filter(Boolean).join(", ") || "—"}
                {propertyData.address?.PostalCode && ` ${propertyData.address.PostalCode}`}
              </p>
              <div className="flex gap-4 pt-1 text-muted-foreground">
                {propertyData.improvements?.BedroomsTotal != null && (
                  <span>{propertyData.improvements.BedroomsTotal} bed{propertyData.improvements.BedroomsTotal !== 1 ? "s" : ""}</span>
                )}
                {propertyData.improvements?.BathroomsFull != null && (
                  <span>{propertyData.improvements.BathroomsFull} bath{propertyData.improvements.BathroomsFull !== 1 ? "s" : ""}</span>
                )}
                {propertyData.improvements?.LivingArea != null && (
                  <span>{propertyData.improvements.LivingArea} sqm</span>
                )}
              </div>
            </div>
          </section>
        )}

        <form className="mt-6 space-y-6" onSubmit={(e) => e.preventDefault()}>
          {/* Style slider 0–100% */}
          <section className="rounded-lg border border-border bg-card p-4 shadow-sm">
            <h2 className="text-base font-bold text-card-foreground font-sans mb-3">
              Style intensity
            </h2>
            <div className="flex items-center gap-4">
              <span className="text-sm font-normal text-muted-foreground font-sans w-8">0%</span>
              <input
                type="range"
                min={0}
                max={100}
                value={styleLevel}
                onChange={(e) => setStyleLevel(Number(e.target.value))}
                className="flex-1 h-2 rounded-full appearance-none bg-muted accent-[#003366]"
              />
              <span className="text-sm font-normal text-muted-foreground font-sans w-10">{styleLevel}%</span>
            </div>
          </section>

          {/* Antipodean style buttons — Director: 48px × 200px, Deep Navy */}
          <section className="rounded-lg border border-border bg-card p-4 shadow-sm">
            <h2 className="text-base font-bold text-card-foreground font-sans mb-3">
              Antipodean styles
            </h2>
            <div className="flex flex-wrap gap-3">
              {ANTIPODEAN_STYLES.map((style) => (
                <Button
                  key={style.id}
                  type="button"
                  onClick={() => setSelectedStyle(selectedStyle === style.id ? null : style.id)}
                  className={`${DIRECTOR_BUTTON_CLASS} ${selectedStyle === style.id ? "ring-2 ring-[#007BFF] ring-offset-2" : ""}`}
                >
                  {style.label}
                </Button>
              ))}
            </div>
          </section>

          {/* Basic Info */}
          <section className="rounded-lg border border-border bg-card p-4 shadow-sm">
            <h2 className="font-bold text-card-foreground font-sans mb-3">Address (RESO 2.0)</h2>
            <div className="grid grid-cols-2 gap-4">
              <input
                {...register("address.StreetNumber")}
                placeholder="Street Number"
                className="border border-border rounded-md px-3 py-2 text-sm font-sans text-card-foreground bg-background"
              />
              <input
                {...register("address.StreetName")}
                placeholder="Street Name"
                className="border border-border rounded-md px-3 py-2 text-sm font-sans text-card-foreground bg-background"
              />
            </div>
            {errors.address?.StreetName && (
              <p className="text-destructive text-xs mt-1 font-sans">{errors.address.StreetName.message}</p>
            )}
          </section>

          <section className="rounded-lg border border-border bg-card p-4 shadow-sm">
            <h2 className="font-bold text-card-foreground font-sans mb-3">Property features</h2>
            <div className="grid grid-cols-3 gap-4">
              <input
                type="number"
                {...register("improvements.BedroomsTotal", { valueAsNumber: true })}
                placeholder="Beds"
                className="border border-border rounded-md px-3 py-2 text-sm font-sans text-card-foreground bg-background"
              />
              <input
                type="number"
                {...register("improvements.BathroomsFull", { valueAsNumber: true })}
                placeholder="Baths"
                className="border border-border rounded-md px-3 py-2 text-sm font-sans text-card-foreground bg-background"
              />
              <input
                type="number"
                {...register("improvements.LivingArea", { valueAsNumber: true })}
                placeholder="Living (sqft)"
                className="border border-border rounded-md px-3 py-2 text-sm font-sans text-card-foreground bg-background"
              />
            </div>
          </section>

          {/* Generate + Download — Director style; generation uses store property data + voice style */}
          <div className="flex flex-wrap items-center gap-3">
            <Button type="button" onClick={generateFromStore} className={DIRECTOR_BUTTON_CLASS}>
              Generate listing copy
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={handleDownloadTxt}
              className="h-[48px] w-[200px] rounded-md font-sans font-medium border-2 border-[#003366] text-[#003366] bg-transparent hover:bg-[#003366]/5 transition-colors"
            >
              Download Plain Text (.txt)
            </Button>
          </div>

          {generatedText && (
            <div className="rounded-lg border-2 border-[#003366] bg-white p-4">
              <h3 className="text-sm font-bold text-[#003366] font-sans mb-2">Generated text</h3>
              <pre className="whitespace-pre-wrap text-sm font-normal text-card-foreground font-sans">
                {generatedText}
              </pre>
            </div>
          )}
        </form>
      </div>
    </DashboardShell>
  );
}
