"use client";

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useState, useCallback } from "react";
import { PropertySchema, type Property } from "@/schemas/property.schema";
import DashboardShell from "@/components/layout/dashboard-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const ANTIPODEAN_STYLES = [
  { id: "contemporary", label: "Contemporary" },
  { id: "heritage", label: "Heritage" },
  { id: "coastal", label: "Coastal" },
  { id: "urban", label: "Urban" },
] as const;

function downloadPlainText(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function DataEntryPage() {
  const [styleSlider, setStyleSlider] = useState(50);
  const [selectedStyle, setSelectedStyle] = useState<string | null>(null);
  const [generatedText, setGeneratedText] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
  } = useForm<Property>({
    resolver: zodResolver(PropertySchema),
    defaultValues: {
      source: "Manual",
      dataConfidence: 5,
      createdAt: new Date(),
      propertyId: "",
      address: {
        StreetNumber: "",
        StreetName: "",
        City: "",
        StateOrProvince: "",
        PostalCode: "",
        Country: "AU",
      },
      improvements: {},
      land: {},
    },
  });

  const address = watch("address");
  const streetLabel = [address?.StreetNumber, address?.StreetName].filter(Boolean).join(" ") || "Property";

  const onSubmit = useCallback(
    (data: Property) => {
      console.log("RESO 2.0 Validated Data:", data);
      const styleName = selectedStyle
        ? ANTIPODEAN_STYLES.find((s) => s.id === selectedStyle)?.label ?? "Contemporary"
        : "Contemporary";
      const mockReport = [
        `Listing Report — ${streetLabel || "New Listing"}`,
        `Style: ${styleName} · Intensity: ${styleSlider}%`,
        "",
        "--- RESO-compliant data ---",
        `Address: ${data.address?.StreetNumber ?? ""} ${data.address?.StreetName ?? ""}, ${data.address?.City ?? ""} ${data.address?.StateOrProvince ?? ""} ${data.address?.PostalCode ?? ""}`,
        `Beds: ${data.improvements?.BedroomsTotal ?? "—"}`,
        `Baths: ${data.improvements?.BathroomsFull ?? "—"}`,
        `Living Area: ${data.improvements?.LivingArea ?? "—"} sqft`,
        "",
        "Generated by RealInfo · RESO-compliant.",
      ].join("\n");
      setGeneratedText(mockReport);
    },
    [selectedStyle, styleSlider, streetLabel]
  );

  const handleDownloadTxt = useCallback(() => {
    if (!generatedText) return;
    const name = streetLabel.replace(/\s+/g, "-").slice(0, 40) || "listing-report";
    downloadPlainText(generatedText, `${name}-${Date.now()}.txt`);
  }, [generatedText, streetLabel]);

  return (
    <DashboardShell>
      <div className="mx-auto max-w-2xl">
        <header className="overflow-hidden rounded-lg border border-border bg-primary text-primary-foreground shadow-sm">
          <div className="px-6 py-5">
            <h1 className="text-xl font-bold tracking-tight font-sans sm:text-2xl">
              Listing Generator
            </h1>
            <p className="mt-1 text-sm font-normal text-primary-foreground/80 font-sans">
              RealInfo · RESO-compliant listing copy in your voice.
            </p>
          </div>
        </header>

        <Card className="mt-6 overflow-hidden rounded-lg border border-border bg-card shadow-sm">
          <CardHeader className="border-b border-border bg-muted/30 px-6 py-4">
            <CardTitle className="text-base font-bold text-card-foreground font-sans">
              Style
            </CardTitle>
            <p className="text-sm font-normal text-muted-foreground font-sans mt-1">
              Slider 0–100% · Antipodean styles
            </p>
          </CardHeader>
          <CardContent className="px-6 py-5 space-y-6">
            <div>
              <label className="block text-sm font-medium text-card-foreground font-sans mb-2">
                Style intensity: {styleSlider}%
              </label>
              <input
                type="range"
                min={0}
                max={100}
                value={styleSlider}
                onChange={(e) => setStyleSlider(Number(e.target.value))}
                className="w-full h-2 rounded-full appearance-none bg-muted accent-[#003366]"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-card-foreground font-sans mb-2">
                Antipodean styles
              </label>
              <div className="flex flex-wrap gap-3">
                {ANTIPODEAN_STYLES.map((style) => (
                  <Button
                    key={style.id}
                    type="button"
                    variant="outline"
                    className={`h-[48px] w-[200px] font-sans font-medium border-2 ${
                      selectedStyle === style.id
                        ? "border-[#003366] bg-[#003366] text-white hover:bg-[#003366]/90"
                        : "border-[#003366] bg-transparent text-[#003366] hover:bg-[#003366]/5"
                    }`}
                    onClick={() => setSelectedStyle(selectedStyle === style.id ? null : style.id)}
                  >
                    {style.label}
                  </Button>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>

        <form onSubmit={handleSubmit(onSubmit)} className="mt-6 space-y-6">
          <Card className="overflow-hidden rounded-lg border border-border bg-card shadow-sm">
            <CardHeader className="border-b border-border bg-muted/30 px-6 py-4">
              <CardTitle className="text-base font-bold text-card-foreground font-sans">
                Address (RESO 2.0)
              </CardTitle>
            </CardHeader>
            <CardContent className="px-6 py-5 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <input
                  {...register("address.StreetNumber")}
                  placeholder="Street Number"
                  className="border border-input rounded-md px-3 py-2 text-sm font-sans bg-background"
                />
                <input
                  {...register("address.StreetName")}
                  placeholder="Street Name"
                  className="border border-input rounded-md px-3 py-2 text-sm font-sans bg-background"
                />
              </div>
              {errors.address?.StreetName && (
                <p className="text-destructive text-xs font-sans">{errors.address.StreetName.message}</p>
              )}
            </CardContent>
          </Card>

          <Card className="overflow-hidden rounded-lg border border-border bg-card shadow-sm">
            <CardHeader className="border-b border-border bg-muted/30 px-6 py-4">
              <CardTitle className="text-base font-bold text-card-foreground font-sans">
                Property Features
              </CardTitle>
            </CardHeader>
            <CardContent className="px-6 py-5">
              <div className="grid grid-cols-3 gap-4">
                <input
                  type="number"
                  {...register("improvements.BedroomsTotal", { valueAsNumber: true })}
                  placeholder="Beds"
                  className="border border-input rounded-md px-3 py-2 text-sm font-sans bg-background"
                />
                <input
                  type="number"
                  {...register("improvements.BathroomsFull", { valueAsNumber: true })}
                  placeholder="Baths"
                  className="border border-input rounded-md px-3 py-2 text-sm font-sans bg-background"
                />
                <input
                  type="number"
                  {...register("improvements.LivingArea", { valueAsNumber: true })}
                  placeholder="Living Area (sqft)"
                  className="border border-input rounded-md px-3 py-2 text-sm font-sans bg-background"
                />
              </div>
            </CardContent>
          </Card>

          <div className="flex flex-wrap items-center gap-3">
            <Button
              type="submit"
              className="h-[48px] w-[200px] bg-[#003366] hover:bg-[#003366]/90 font-sans font-medium text-white"
            >
              Generate Listing Report
            </Button>
            <Button
              type="button"
              variant="outline"
              disabled={!generatedText}
              onClick={handleDownloadTxt}
              className="h-[48px] w-[200px] font-sans font-medium border-2 border-[#003366] text-[#003366] bg-transparent hover:bg-[#003366]/5 disabled:opacity-50"
            >
              Download Plain Text (.txt)
            </Button>
          </div>
        </form>

        {generatedText && (
          <Card className="mt-6 overflow-hidden rounded-lg border-2 border-[#003366] bg-white shadow-sm">
            <CardHeader className="border-b border-[#003366]/20 bg-[#003366] px-6 py-3">
              <CardTitle className="text-base font-bold text-white font-sans">
                RealInfo | Listing Report
              </CardTitle>
            </CardHeader>
            <CardContent className="px-6 py-4">
              <pre className="whitespace-pre-wrap text-sm font-normal text-[#003366] font-sans leading-relaxed">
                {generatedText}
              </pre>
            </CardContent>
          </Card>
        )}
      </div>
    </DashboardShell>
  );
}
