"use client";

import { useState, useCallback } from "react";
import Link from "next/link";
import DashboardShell from "@/components/layout/dashboard-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { usePropertyEntry, useVoiceSettings, ANTIPODEAN_STYLES } from "@/contexts/listing-context";

function downloadPlainText(content: string, filename: string = "listing-copy.txt") {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function buildReportFromContext(
  property: { address?: { StreetNumber?: string; StreetName?: string; City?: string; PostalCode?: string }; improvements?: { BedroomsTotal?: number; BathroomsFull?: number; LivingArea?: number } } | null,
  styleId: string | null,
  styleIntensity: number
): string {
  if (!property?.address) {
    return "";
  }
  const addr = [property.address?.StreetNumber, property.address?.StreetName].filter(Boolean).join(" ");
  const city = property.address?.City || "";
  const postcode = property.address?.PostalCode || "";
  const beds = property.improvements?.BedroomsTotal ?? "";
  const baths = property.improvements?.BathroomsFull ?? "";
  const styleLabel = ANTIPODEAN_STYLES.find((s) => s.id === styleId)?.label ?? "General";
  return [
    `${addr}${city ? `, ${city}` : ""}${postcode ? ` ${postcode}` : ""}`,
    "",
    `Style: ${styleLabel} · Intensity: ${styleIntensity}%`,
    beds !== "" ? `${beds} bedrooms` : "",
    baths !== "" ? `${baths} bathrooms` : "",
    "",
    "Generated by RealInfo Listing Generator. RESO-compliant data.",
  ]
    .filter(Boolean)
    .join("\n");
}

export default function DataEntryPage() {
  const { property } = usePropertyEntry();
  const { voice } = useVoiceSettings();
  const [generatedText, setGeneratedText] = useState<string>("");

  const { styleId, styleIntensity } = voice;

  const onGenerate = useCallback(() => {
    const report = buildReportFromContext(property, styleId, styleIntensity);
    setGeneratedText(report);
  }, [property, styleId, styleIntensity]);

  const handleDownloadTxt = useCallback(() => {
    const text =
      generatedText || "No listing copy generated yet. Generate using property and voice data.";
    downloadPlainText(text);
  }, [generatedText]);

  const hasProperty = Boolean(property?.address?.StreetNumber || property?.address?.StreetName || property?.address?.City);

  return (
    <DashboardShell>
      <div className="mx-auto max-w-2xl">
        <header className="overflow-hidden rounded-lg border border-border bg-primary text-primary-foreground shadow-sm">
          <div className="px-6 py-5">
            <h1 className="text-xl font-bold tracking-tight font-sans sm:text-2xl">
              Listing Generator
            </h1>
            <p className="mt-1 text-sm font-normal text-primary-foreground/80 font-sans">
              RealInfo · RESO-compliant. Your signature voice, AI-powered.
            </p>
          </div>
        </header>

        {!hasProperty && (
          <Card className="mt-6 overflow-hidden rounded-lg border border-amber-500/50 bg-amber-500/5 shadow-sm">
            <CardContent className="px-6 py-4">
              <p className="text-sm font-sans text-card-foreground mb-3">
                No property data yet. Enter a property first, then come back to generate the listing.
              </p>
              <Link href="/property-entry">
                <Button
                  type="button"
                  className="h-[40px] rounded-md bg-[#003366] font-sans font-medium text-white hover:bg-[#003366]/90"
                >
                  Go to Property Entry
                </Button>
              </Link>
            </CardContent>
          </Card>
        )}

        <div className="mt-6 flex flex-wrap items-center gap-3">
          <Button
            type="button"
            onClick={onGenerate}
            disabled={!hasProperty}
            className="h-[48px] w-[200px] rounded-md bg-[#003366] font-sans font-medium text-white hover:bg-[#003366]/90 disabled:opacity-50"
          >
            Generate Listing Report
          </Button>
          <Button
            type="button"
            onClick={handleDownloadTxt}
            className="h-[48px] w-[200px] rounded-md border-2 border-[#003366] bg-transparent font-sans font-medium text-[#003366] hover:bg-[#003366]/5"
          >
            Download Plain Text (.txt)
          </Button>
        </div>

        <p className="mt-3 text-sm text-muted-foreground font-sans">
          Property data from{" "}
          <Link href="/property-entry" className="text-[#007BFF] hover:underline">
            Property Entry
          </Link>
          ; tone from{" "}
          <Link href="/voice-training" className="text-[#007BFF] hover:underline">
            Voice Training
          </Link>
          .
        </p>

        {generatedText && (
          <Card className="mt-6 overflow-hidden rounded-lg border-2 border-[#003366] bg-white shadow-sm">
            <CardHeader className="border-b border-[#003366]/20 bg-[#003366] px-6 py-3">
              <CardTitle className="text-base font-bold text-white font-sans">
                RealInfo | Generated copy
              </CardTitle>
            </CardHeader>
            <CardContent className="px-6 py-4">
              <pre className="whitespace-pre-wrap text-sm font-normal leading-relaxed text-[#003366] font-sans">
                {generatedText}
              </pre>
            </CardContent>
          </Card>
        )}
      </div>
    </DashboardShell>
  );
}
