"use server";

import { GoogleGenerativeAI } from "@google/generative-ai";
import { getPropertyById } from "./properties";
import type { Property } from "@/schemas/property.schema";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

/** Build prompt data from store Property (form data). */
function propertyDataToPromptInput(propertyData: Property) {
  const addr = propertyData.address;
  const imp = propertyData.improvements ?? {};
  const addressLine = [addr?.StreetNumber, addr?.StreetName].filter(Boolean).join(" ").trim() || "—";
  const suburb = addr?.City ?? "—";
  const g = imp.GarageCount ?? 0;
  const c = imp.CarportCount ?? 0;
  const s = imp.StandaloneShedBays ?? 0;
  const parkingCount = g + c + s;
  return {
    address: addressLine,
    suburb,
    livingArea: imp.LivingArea ?? null,
    garageSpaces: g,
    carPortSpaces: c,
    parkingCount,
    keyFeatures: propertyData.keyFeatures ?? [],
    primarySchoolCatchment: propertyData.identity?.schoolCatchment ?? addr?.PrimarySchoolCatchment ?? null,
  };
}

export async function generateAiListing(
  propertyId: string | null,
  propertyData: Property | null,
  style: string
): Promise<{ ok: true; content: string } | { ok: false; error: string }> {
  let address: string;
  let suburb: string;
  let livingArea: number | null;
  let garageSpaces: number;
  let carPortSpaces: number;
  let keyFeatures: string[];
  let primarySchoolCatchment: string | null;

  if (propertyId) {
    const property = await getPropertyById(propertyId);
    if (!property) return { ok: false, error: "Property not found" };
    address = property.address;
    suburb = property.suburb;
    livingArea = property.livingArea;
    garageSpaces = property.garageSpaces ?? 0;
    carPortSpaces = property.carPortSpaces ?? 0;
    keyFeatures = property.keyFeatures ?? [];
    primarySchoolCatchment = property.primarySchoolCatchment;
  } else if (propertyData?.address) {
    const input = propertyDataToPromptInput(propertyData);
    address = input.address;
    suburb = input.suburb;
    livingArea = input.livingArea;
    garageSpaces = input.garageSpaces;
    carPortSpaces = input.carPortSpaces;
    keyFeatures = input.keyFeatures;
    primarySchoolCatchment = input.primarySchoolCatchment;
  } else {
    return { ok: false, error: "No property data. Add address and features on Property Entry first." };
  }

  // The most reliable "Stable" model for high-volume tasks in 2026
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

  const featuresStr = keyFeatures.length ? keyFeatures.join(", ") : "Standard residential features";
  const livingStr = livingArea != null && livingArea > 0 ? `${livingArea}m²` : "—";

  const prompt = `
    You are an elite Australian real estate copywriter. Write a compelling property listing in a ${style} style.
    
    DATA SET (RESO-compliant):
    - Address: ${address}, ${suburb}
    - Living Area: ${livingStr}
    - Parking: ${garageSpaces} Garage, ${carPortSpaces} Carports
    - Features: ${featuresStr}
    - Schools: ${primarySchoolCatchment ?? "—"}
    
    TONE GUIDELINES:
    - Coastal: Use airy, light, relaxed language. Mention the sea breeze and lifestyle.
    - Executive: Focus on prestige, luxury finishes, and the "power" of the location.
    - Contemporary: Clean, modern, minimalist language.
    - Heritage: Emphasise character, period features, and timeless appeal.
    - Urban: Highlight convenience, connectivity, and inner-city living.
    
    Structure the output with a catchy Headline, a Body Paragraph, and a Bulleted Feature List.
    End with: "Generated by RealInfo Listing Generator (RESO-compliant)."
  `;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return { ok: true, content: response.text() };
  } catch (error: any) {
    console.error("AI Generation failed:", error);
    // This will show us the EXACT error from Google (e.g., "Invalid API Key" or "Quota Exceeded")
    return { ok: false, error: `Google says: ${error.message || "Unknown Connection Error"}` };
  }

}
