"use server";

import { db } from "@/db";
import { propertyAnalysis, properties } from "@/db/schema";
import { eq, desc } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { GoogleGenerativeAI } from "@google/generative-ai";

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export type PropertyAnalysisRow = {
  id: string;
  propertyId: string;
  type: string;
  content: string;
  metadata: unknown;
  createdAt: Date;
};

/** Shape for AI content generation (DB row or mapped from form/store). */
type PropertyForAi = {
  address: string;
  suburb: string;
  bedCount: number | null;
  bathCount: number | null;
  parkingCount: number | null;
  keyFeatures?: string[] | null;
  livingArea?: number | null;
};

/**
 * THE BRAIN: This talks to Gemini using the RESO data.
 */
async function generateAiContent(property: PropertyForAi, style: string = "Coastal"): Promise<string> {
  const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

  const specs = [
    property.bedCount != null && property.bedCount > 0 ? `${property.bedCount} Bed` : null,
    property.bathCount != null && property.bathCount > 0 ? `${property.bathCount} Bath` : null,
    property.parkingCount != null && property.parkingCount > 0 ? `${property.parkingCount} Car` : null,
  ]
    .filter(Boolean)
    .join(", ");
  const features = property.keyFeatures?.length
    ? property.keyFeatures.join(", ")
    : "Standard residential features";
  const livingArea = property.livingArea != null && property.livingArea > 0 ? `${property.livingArea}m²` : "—";

  const prompt = `
    You are an expert Australian Real Estate Copywriter. 
    Write a high-end property listing for the following RESO-compliant data.
    
    STYLE: ${style}
    ADDRESS: ${property.address}, ${property.suburb}
    SPECS: ${specs || "—"}
    FEATURES: ${features}.
    LIVING AREA: ${livingArea}.

    REQUIREMENTS:
    - Headline: Catchy and style-specific.
    - Body: 3 paragraphs of emotive, punchy copy.
    - Features: A bulleted list of 5 key highlights.
    - End with: "Generated by RealInfo Listing Generator (RESO-compliant)."
  `;

  try {
    const result = await model.generateContent(prompt);
    return result.response.text();
  } catch (err) {
    console.error("Gemini Error:", err);
    return "Error generating AI content. Please check API key.";
  }
}

/** Generate a vendor strategy using AI and save to DB. */
export async function generateVendorStrategy(propertyId: string, style: string = "Coastal"): Promise<
  | { ok: true; analysisId: string; content: string }
  | { ok: false; error: string }
> {
  try {
    // 1. Fetch the data (including our new 3NF columns)
    const [property] = await db
      .select()
      .from(properties)
      .where(eq(properties.id, propertyId))
      .limit(1);

    if (!property) return { ok: false, error: "Property not found." };

    // 2. GET THE AI CONTENT (The magic happens here)
    const content = await generateAiContent(property, style);

    // 3. Save to the analysis table
    const [inserted] = await db
      .insert(propertyAnalysis)
      .values({
        propertyId,
        type: "vendor_strategy",
        content,
        metadata: { 
          source: "gemini-1.5-flash", 
          style, 
          propertyAddress: property.address 
        },
      })
      .returning({ id: propertyAnalysis.id });

    if (!inserted) return { ok: false, error: "Failed to save analysis." };

    revalidatePath(`/properties/${propertyId}`);
    return { ok: true, analysisId: inserted.id, content };
  } catch (err) {
    console.error("generateVendorStrategy:", err);
    return { ok: false, error: err instanceof Error ? err.message : "Failed." };
  }
}

/**
 * Generate listing copy from form/store property data (no DB save required).
 * Use when the user has propertyData in the store but no activePropertyId.
 */
export async function generateListingFromStore(
  propertyData: {
    address?: { StreetNumber?: string; StreetName?: string; City?: string; StateOrProvince?: string; PostalCode?: string } | null;
    improvements?: {
      BedroomsTotal?: number;
      BathroomsFull?: number;
      LivingArea?: number;
      GarageCount?: number;
      CarportCount?: number;
      StandaloneShedBays?: number;
    } | null;
    keyFeatures?: string[] | null;
  } | null,
  style: string = "Coastal"
): Promise<{ ok: true; content: string } | { ok: false; error: string }> {
  if (!propertyData?.address) {
    return { ok: false, error: "No property data. Add address and features on Property Entry first." };
  }

  const addr = propertyData.address;
  const imp = propertyData.improvements ?? {};
  const addressLine = [addr.StreetNumber, addr.StreetName].filter(Boolean).join(" ").trim() || "—";
  const suburb = addr.City?.trim() ?? "—";
  const g = imp.GarageCount ?? 0;
  const c = imp.CarportCount ?? 0;
  const s = imp.StandaloneShedBays ?? 0;
  const parkingCount = g + c + s;

  const forAi: PropertyForAi = {
    address: addressLine,
    suburb,
    bedCount: imp.BedroomsTotal ?? null,
    bathCount: imp.BathroomsFull ?? null,
    parkingCount: parkingCount > 0 ? parkingCount : null,
    keyFeatures: propertyData.keyFeatures ?? [],
    livingArea: imp.LivingArea ?? null,
  };

  try {
    const content = await generateAiContent(forAi, style);
    return { ok: true, content };
  } catch (err) {
    console.error("generateListingFromStore:", err);
    return { ok: false, error: err instanceof Error ? err.message : "Failed to generate." };
  }
}

/** Fetch all analyses for a property (unchanged) */
export async function getAnalysesByPropertyId(propertyId: string): Promise<PropertyAnalysisRow[]> {
  try {
    const rows = await db
      .select()
      .from(propertyAnalysis)
      .where(eq(propertyAnalysis.propertyId, propertyId))
      .orderBy(desc(propertyAnalysis.createdAt));

    return rows as PropertyAnalysisRow[];
  } catch (error) {
    return [];
  }
}
